---
name: Linter

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linter:
    name: Linter
    uses: raven-actions/.workflows/.github/workflows/__linter.yml@6da075fe5a370a05993c72f0a7b7dd109389e691 # main
    secrets: inherit
